---

- hosts: all
  gather_facts: no
  vars:
     pip_packages: "{{ lookup('file', './requirements.txt') }}"

  tasks:
   - pip: 
        name: "{{item}}"
     become: yes
     with_items: ["azure-common", "azure-mgmt-compute", "azure-mgmt-network" ,"configparser"]