---
- hosts: all

  gather_facts: no
  tasks:
  - shell: git clone https://github.com/lukemgriffith/Azure.Infrastructure && cd Azure.Infrastructure && terraform apply
    register: log

  - debug:
      msg: log